MEMORY
{
  /* RAM is actually 128K, but reserve top 32K for WF200 C-FFI buffers */
  RAM : ORIGIN = 0x10000000, LENGTH = 96K
  FLASH : ORIGIN = 0x2001A000, LENGTH = 16M
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);